project:
  type: website
  output-dir: docs
  execute-dir: project
  resources:
    - "_targets.R"

website:
  title: "Statistical Rethinking colearning 2024"
  repo-url: https://github.com/robitalec/statistical-rethinking-colearning-2024
  repo-actions: [edit, issue]

  sidebar:
    contents:
      - text: "Home"
        file: index.qmd
      - section: Notes
        contents:
          - auto: "notes/*"
      - section: Homework
        contents:
          - auto: "homework/*"
    tools:
      - icon: github
        href: https://github.com/robitalec/statistical-rethinking-colearning-2024

format:
  html:
    theme:
      dark: darkly
      light: flatly
    toc: true
    code-line-numbers: false
    code-copy: true
    code-link: true
    code-block-border-left: false
